const artistsData = [

{"artistName":"Ahin","groupName":"Momoland","imageName":"AHIN_MOMOLAND","birthday":"27/09/1999","birthdayNumber":19990927,"age":24,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Ahyeon","groupName":"Babymonster","imageName":"AHYEON_BABYMONSTER","birthday":"11/04/2007","birthdayNumber":20070411,"age":16,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Aisha","groupName":"Everglow","imageName":"AISHA_EVERGLOW","birthday":"21/07/2000","birthdayNumber":20000721,"age":23,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Ara","groupName":"ily:1","imageName":"ARA_ILY1","birthday":"23/01/2002","birthdayNumber":20020123,"age":21,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Arin","groupName":"Oh My Girl","imageName":"ARIN_OHMYGIRL","birthday":"18/06/1999","birthdayNumber":19990618,"age":24,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Asa","groupName":"Babymonster","imageName":"ASA_BABYMONSTER","birthday":"17/04/2006","birthdayNumber":20060417,"age":17,"countryId":5,"country":"Japan","zodiacId":1,"zodiac":"Aries","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Bae","groupName":"NMIXX","imageName":"BAE_NMIXX","birthday":"28/12/2004","birthdayNumber":20041228,"age":19,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Bahiyyih","groupName":"Kep1er","imageName":"BAHIYYIH_KEP1ER","birthday":"27/07/2004","birthdayNumber":20040727,"age":19,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Belle","groupName":"cignature","imageName":"BELLE_CIGNATURE","birthday":"03/11/2001","birthdayNumber":20011103,"age":22,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Belle","groupName":"KISS OF LIFE","imageName":"BELLE_KISSOFLIFE","birthday":"20/03/2004","birthdayNumber":20040320,"age":19,"countryId":8,"country":"USA","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Bian","groupName":"others","imageName":"BIAN_OTHERS","birthday":"13/02/2001","birthdayNumber":20010213,"age":22,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Boeun","groupName":"CLASS:y","imageName":"BOEUN_CLASSY","birthday":"11/02/2008","birthdayNumber":20080211,"age":15,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Boni","groupName":"Dream Note","imageName":"BONI_DREAMNOTE","birthday":"30/10/1999","birthdayNumber":19991030,"age":24,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Bora","groupName":"Cherry Bullet","imageName":"BORA_CHERRYBULLET","birthday":"03/03/1999","birthdayNumber":19990303,"age":24,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Chaeeun","groupName":"ADYA","imageName":"CHAEEUN_ADYA","birthday":"10/12/2005","birthdayNumber":20051210,"age":18,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Chaehyun","groupName":"Kep1er","imageName":"CHAEHYUN_KEP1ER","birthday":"26/04/2002","birthdayNumber":20020426,"age":21,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Chaein","groupName":"Purple Kiss","imageName":"CHAEIN_PURPLEKISS","birthday":"05/12/2002","birthdayNumber":20021205,"age":21,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Chaerin","groupName":"Cherry Bullet","imageName":"CHAERIN_CHERRYBULLET","birthday":"13/03/2002","birthdayNumber":20020313,"age":21,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Chaerin","groupName":"ichillin","imageName":"CHAERIN_ICHILLIN","birthday":"31/03/2003","birthdayNumber":20030331,"age":20,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Chaeryeong","groupName":"ITZY","imageName":"CHAERYEONG_ITZY","birthday":"05/06/2001","birthdayNumber":20010605,"age":22,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Chaesol","groupName":"cignature","imageName":"CHAESOL_CIGNATURE","birthday":"14/07/1998","birthdayNumber":19980714,"age":25,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"Chaewon","groupName":"LE SSERAFIM","imageName":"CHAEWON_LESSERAFIM","birthday":"01/08/2000","birthdayNumber":20000801,"age":23,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Chaewon","groupName":"CLASS:y","imageName":"CHAEWON_CLASSY","birthday":"04/06/2003","birthdayNumber":20030604,"age":20,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Chaeyeon","groupName":"tripleS","imageName":"CHAEYEON_TRIPLES","birthday":"04/12/2004","birthdayNumber":20041204,"age":19,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Chaeyeon","groupName":"soloist","imageName":"CHAEYEON_SOLOIST","birthday":"11/01/2000","birthdayNumber":20000111,"age":23,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Chaeyoung","groupName":"fromis_9","imageName":"CHAEYOUNG_FROMIS9","birthday":"14/05/2000","birthdayNumber":20000514,"age":23,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Chanty","groupName":"Lapillus","imageName":"CHANTY_LAPILLUS","birthday":"15/12/2002","birthdayNumber":20021215,"age":21,"countryId":9,"country":"Phillipines","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Chloe","groupName":"cignature","imageName":"CHLOE_CIGNATURE","birthday":"06/01/2001","birthdayNumber":20010106,"age":23,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Choerry","groupName":"ARTMS","imageName":"CHOERRY_ARTMS","birthday":"04/06/2001","birthdayNumber":20010604,"age":22,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Chowon","groupName":"ichillin","imageName":"CHOWON_ICHILLIN","birthday":"18/08/2005","birthdayNumber":20050818,"age":18,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Chowon","groupName":"Lightsum","imageName":"CHOWON_LIGHTSUM","birthday":"16/09/2002","birthdayNumber":20020916,"age":21,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Choyeon","groupName":"bugAboo","imageName":"CHOYEON_BUGABOO","birthday":"01/08/2001","birthdayNumber":20010801,"age":22,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Chungha","groupName":"soloist","imageName":"CHUNGHA_SOLOIST","birthday":"09/02/1996","birthdayNumber":19960209,"age":27,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Chuu","groupName":"soloist","imageName":"CHUU_SOLOIST","birthday":"20/10/1999","birthdayNumber":19991020,"age":24,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Cocona","groupName":"XG","imageName":"COCONA_XG","birthday":"06/12/2005","birthdayNumber":20051206,"age":18,"countryId":5,"country":"Japan","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Dahyun","groupName":"Rocket Punch","imageName":"DAHYUN_ROCKETPUNCH","birthday":"29/04/2005","birthdayNumber":20050429,"age":18,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Dahyun","groupName":"tripleS","imageName":"DAHYUN_TRIPLES","birthday":"08/01/2003","birthdayNumber":20030108,"age":21,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Dajeong","groupName":"Pixy","imageName":"DAJEONG_PIXY","birthday":"31/07/2003","birthdayNumber":20030731,"age":20,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Danielle","groupName":"NewJeans","imageName":"DANIELLE_NEWJEANS","birthday":"11/04/2005","birthdayNumber":20050411,"age":18,"countryId":11,"country":"Australia","zodiacId":1,"zodiac":"Aries","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Dayeon","groupName":"Kep1er","imageName":"DAYEON_KEP1ER","birthday":"02/03/2003","birthdayNumber":20030302,"age":20,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Dia","groupName":"Pixy","imageName":"DIA_PIXY","birthday":"16/07/2001","birthdayNumber":20010716,"age":22,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Dosie","groupName":"Purple Kiss","imageName":"DOSIE_PURPLEKISS","birthday":"11/02/2000","birthdayNumber":20000211,"age":23,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Duna","groupName":"CSR","imageName":"DUNA_CSR","birthday":"28/04/2005","birthdayNumber":20050428,"age":18,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"E:U","groupName":"Everglow","imageName":"EU_EVERGLOW","birthday":"19/05/1998","birthdayNumber":19980519,"age":25,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"E.JI","groupName":"ichillin","imageName":"EJI_ICHILLIN","birthday":"08/11/2000","birthdayNumber":20001108,"age":23,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Elva","groupName":"ily:1","imageName":"ELVA_ILY1","birthday":"05/05/2003","birthdayNumber":20030505,"age":20,"countryId":3,"country":"Taiwan","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Eunbi","groupName":"soloist","imageName":"EUNBI_SOLOIST","birthday":"27/09/1995","birthdayNumber":19950927,"age":28,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Eunchae","groupName":"bugAboo","imageName":"EUNCHAE_BUGABOO","birthday":"06/10/1999","birthdayNumber":19991006,"age":24,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Eunchae","groupName":"LE SSERAFIM","imageName":"EUNCHAE_LESSERAFIM","birthday":"10/11/2006","birthdayNumber":20061110,"age":17,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Eunha","groupName":"VIVIZ","imageName":"EUNHA_VIVIZ","birthday":"30/05/1997","birthdayNumber":19970530,"age":26,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Eunjo","groupName":"Dream Note","imageName":"EUNJO_DREAMNOTE","birthday":"07/03/2002","birthdayNumber":20020307,"age":21,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Eunseo","groupName":"WJSN","imageName":"EUNSEO_WJSN","birthday":"27/05/1998","birthdayNumber":19980527,"age":25,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"Exy","groupName":"WJSN","imageName":"EXY_WJSN","birthday":"06/11/1995","birthdayNumber":19951106,"age":28,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Gaeul","groupName":"IVE","imageName":"GAEUL_IVE","birthday":"24/09/2002","birthdayNumber":20020924,"age":21,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Gahyeon","groupName":"Dreamcatcher","imageName":"GAHYEON_DREAMCATCHER","birthday":"03/02/1999","birthdayNumber":19990203,"age":24,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Garam","groupName":"LE SSERAFIM","imageName":"GARAM_LESSERAFIM","birthday":"16/11/2005","birthdayNumber":20051116,"age":18,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Geumhee","groupName":"CSR","imageName":"GEUMHEE_CSR","birthday":"04/03/2005","birthdayNumber":20050304,"age":18,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Giselle","groupName":"aespa","imageName":"GISELLE_AESPA","birthday":"30/10/2000","birthdayNumber":20001030,"age":23,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Goeun","groupName":"Purple Kiss","imageName":"GOEUN_PURPLEKISS","birthday":"03/09/1999","birthdayNumber":19990903,"age":24,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Gowon","groupName":"LOOSSEMBLE","imageName":"GOWON_LOOSSEMBLE","birthday":"19/11/2000","birthdayNumber":20001119,"age":23,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Gyuri","groupName":"soloist","imageName":"GYURI_SOLOIST","birthday":"27/12/1997","birthdayNumber":19971227,"age":26,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Haerin","groupName":"NewJeans","imageName":"HAERIN_NEWJEANS","birthday":"15/05/2006","birthdayNumber":20060515,"age":17,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Haeun","groupName":"Lapillus","imageName":"HAEUN_LAPILLUS","birthday":"02/11/2008","birthdayNumber":20081102,"age":15,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Haewon","groupName":"NMIXX","imageName":"HAEWON_NMIXX","birthday":"25/02/2003","birthdayNumber":20030225,"age":20,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Handong","groupName":"Dreamcatcher","imageName":"HANDONG_DREAMCATCHER","birthday":"26/03/1996","birthdayNumber":19960326,"age":27,"countryId":4,"country":"China","zodiacId":1,"zodiac":"Aries","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Hanni","groupName":"NewJeans","imageName":"HANNI_NEWJEANS","birthday":"06/10/2004","birthdayNumber":20041006,"age":19,"countryId":11,"country":"Australia","zodiacId":7,"zodiac":"Libra","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Haram","groupName":"Billlie","imageName":"HARAM_BILLLIE","birthday":"13/01/2001","birthdayNumber":20010113,"age":22,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Haruna","groupName":"Billlie","imageName":"HARUNA_BILLLIE","birthday":"30/01/2006","birthdayNumber":20060130,"age":17,"countryId":5,"country":"Japan","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Haseul","groupName":"ARTMS","imageName":"HASEUL_ARTMS","birthday":"18/08/1997","birthdayNumber":19970818,"age":26,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Hayeon","groupName":"tripleS","imageName":"HAYEON_TRIPLES","birthday":"01/08/2007","birthdayNumber":20070801,"age":16,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Hayoung","groupName":"fromis_9","imageName":"HAYOUNG_FROMIS9","birthday":"29/09/1997","birthdayNumber":19970929,"age":26,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Heejin","groupName":"ARTMS","imageName":"HEEJIN_ARTMS","birthday":"19/10/2000","birthdayNumber":20001019,"age":23,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Hikaru","groupName":"Kep1er","imageName":"HIKARU_KEP1ER","birthday":"12/03/2004","birthdayNumber":20040312,"age":19,"countryId":5,"country":"Japan","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Hina","groupName":"Lightsum","imageName":"HINA_LIGHTSUM","birthday":"07/04/2003","birthdayNumber":20030407,"age":20,"countryId":5,"country":"Japan","zodiacId":1,"zodiac":"Aries","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Hinata","groupName":"XG","imageName":"HINATA_XG","birthday":"11/06/2002","birthdayNumber":20020611,"age":21,"countryId":5,"country":"Japan","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Hitomi","groupName":"soloist","imageName":"HITOMI_SOLOIST","birthday":"06/10/2001","birthdayNumber":20011006,"age":22,"countryId":5,"country":"Japan","zodiacId":7,"zodiac":"Libra","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Hwiseo","groupName":"H1-KEY","imageName":"HWISEO_H1KEY","birthday":"31/07/2002","birthdayNumber":20020731,"age":21,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Hyein","groupName":"NewJeans","imageName":"HYEIN_NEWJEANS","birthday":"21/04/2008","birthdayNumber":20080421,"age":15,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Hyeju","groupName":"CLASS:y","imageName":"HYEJU_CLASSY","birthday":"09/12/2003","birthdayNumber":20031209,"age":20,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Hyeju","groupName":"LOOSSEMBLE","imageName":"HYEJU_LOOSSEMBLE","birthday":"13/11/2001","birthdayNumber":20011113,"age":22,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Hyewon","groupName":"soloist","imageName":"HYEWON_SOLOIST","birthday":"05/07/1999","birthdayNumber":19990705,"age":24,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Hyojung","groupName":"Oh My Girl","imageName":"HYOJUNG_OHMYGIRL","birthday":"28/07/1994","birthdayNumber":19940728,"age":29,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Hyunbin","groupName":"TRI.BE","imageName":"HYUNBIN_TRIBE","birthday":"26/05/2004","birthdayNumber":20040526,"age":19,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Hyungseo","groupName":"CLASS:y","imageName":"HYUNGSEO_CLASSY","birthday":"25/06/2001","birthdayNumber":20010625,"age":22,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Hyunjin","groupName":"LOOSSEMBLE","imageName":"HYUNJIN_LOOSSEMBLE","birthday":"15/11/2000","birthdayNumber":20001115,"age":23,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Ireh","groupName":"Purple Kiss","imageName":"IREH_PURPLEKISS","birthday":"30/04/2002","birthdayNumber":20020430,"age":21,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Iroha","groupName":"I\u0027LL-IT","imageName":"IROHA_ILLIT","birthday":"04/02/2008","birthdayNumber":20080204,"age":15,"countryId":5,"country":"Japan","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"ISA","groupName":"Stayc","imageName":"ISA_STAYC","birthday":"23/01/2002","birthdayNumber":20020123,"age":21,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"J","groupName":"Stayc","imageName":"J_STAYC","birthday":"09/12/2004","birthdayNumber":20041209,"age":19,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Jackie","groupName":"ichillin","imageName":"JACKIE_ICHILLIN","birthday":"17/11/2001","birthdayNumber":20011117,"age":22,"countryId":8,"country":"USA","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Jaehee","groupName":"Weeekly","imageName":"JAEHEE_WEEEKLY","birthday":"18/03/2004","birthdayNumber":20040318,"age":19,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Jeewon","groupName":"cignature","imageName":"JEEWON_CIGNATURE","birthday":"01/04/1999","birthdayNumber":19990401,"age":24,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Jennie","groupName":"Blackpink","imageName":"JENNIE_BLACKPINK","birthday":"16/01/1996","birthdayNumber":19960116,"age":27,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Jia","groupName":"TRI.BE","imageName":"JIA_TRIBE","birthday":"30/07/2005","birthdayNumber":20050730,"age":18,"countryId":3,"country":"Taiwan","zodiacId":5,"zodiac":"Leo","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Jia","groupName":"mimiirose","imageName":"JIA_MIMIIROSE","birthday":"16/01/2004","birthdayNumber":20040116,"age":19,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Jieun","groupName":"Purple Kiss","imageName":"JIEUN_PURPLEKISS","birthday":"04/09/1997","birthdayNumber":19970904,"age":26,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Jihan","groupName":"Weeekly","imageName":"JIHAN_WEEEKLY","birthday":"12/07/2004","birthdayNumber":20040712,"age":19,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Jiheon","groupName":"fromis_9","imageName":"JIHEON_FROMIS9","birthday":"17/04/2003","birthdayNumber":20030417,"age":20,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Jiho","groupName":"Oh My Girl","imageName":"JIHO_OHMYGIRL","birthday":"04/04/1997","birthdayNumber":19970404,"age":26,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Jihyo","groupName":"Twice","imageName":"JIHYO_TWICE","birthday":"01/02/1997","birthdayNumber":19970201,"age":26,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Jimin","groupName":"CLASS:y","imageName":"JIMIN_CLASSY","birthday":"25/11/2007","birthdayNumber":20071125,"age":16,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Jinha","groupName":"TRI.BE","imageName":"JINHA_TRIBE","birthday":"21/11/2003","birthdayNumber":20031121,"age":20,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Jini","groupName":"soloist","imageName":"JINI_SOLOIST","birthday":"16/04/2004","birthdayNumber":20040416,"age":19,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Jinny","groupName":"Secret Number","imageName":"JINNY_SECRETNUMBER","birthday":"20/01/1998","birthdayNumber":19980120,"age":25,"countryId":8,"country":"USA","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"Jinsoul","groupName":"ARTMS","imageName":"JINSOUL_ARTMS","birthday":"13/06/1997","birthdayNumber":19970613,"age":26,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Jisoo","groupName":"Blackpink","imageName":"JISOO_BLACKPINK","birthday":"03/01/1995","birthdayNumber":19950103,"age":29,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Jisun","groupName":"fromis_9","imageName":"JISUN_FROMIS9","birthday":"23/11/1998","birthdayNumber":19981123,"age":25,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"Jiu","groupName":"Dreamcatcher","imageName":"JIU_DREAMCATCHER","birthday":"17/05/1994","birthdayNumber":19940517,"age":29,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Jiwon","groupName":"Cherry Bullet","imageName":"JIWON_CHERRYBULLET","birthday":"04/09/2000","birthdayNumber":20000904,"age":23,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Jiwon","groupName":"fromis_9","imageName":"JIWON_FROMIS9","birthday":"20/03/1998","birthdayNumber":19980320,"age":25,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"Jiwoo","groupName":"tripleS","imageName":"JIWOO_TRIPLES","birthday":"24/10/2005","birthdayNumber":20051024,"age":18,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Jiwoo","groupName":"NMIXX","imageName":"JIWOO_NMIXX","birthday":"13/04/2005","birthdayNumber":20050413,"age":18,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Jiyoon","groupName":"ichillin","imageName":"JIYOON_ICHILLIN","birthday":"15/09/2000","birthdayNumber":20000915,"age":23,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Jiyoon","groupName":"Weeekly","imageName":"JIYOON_WEEEKLY","birthday":"02/03/2002","birthdayNumber":20020302,"age":21,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Joobin","groupName":"tripleS","imageName":"JOOBIN_TRIPLES","birthday":"16/01/2009","birthdayNumber":20090116,"age":14,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Jooe","groupName":"Momoland","imageName":"JOOE_MOMOLAND","birthday":"18/08/1999","birthdayNumber":19990818,"age":24,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Joy","groupName":"Red Velvet","imageName":"JOY_REDVELVET","birthday":"03/09/1996","birthdayNumber":19960903,"age":27,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Juhyeon","groupName":"Lightsum","imageName":"JUHYEON_LIGHTSUM","birthday":"08/04/2004","birthdayNumber":20040408,"age":19,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Julie","groupName":"KISS OF LIFE","imageName":"JULIE_KISSOFLIFE","birthday":"29/03/2000","birthdayNumber":20000329,"age":23,"countryId":8,"country":"USA","zodiacId":1,"zodiac":"Aries","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Juri","groupName":"Rocket Punch","imageName":"JURI_ROCKETPUNCH","birthday":"03/10/1997","birthdayNumber":19971003,"age":26,"countryId":5,"country":"Japan","zodiacId":7,"zodiac":"Libra","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Karina","groupName":"aespa","imageName":"KARINA_AESPA","birthday":"11/04/2000","birthdayNumber":20000411,"age":23,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Kazuha","groupName":"LE SSERAFIM","imageName":"KAZUHA_LESSERAFIM","birthday":"09/08/2003","birthdayNumber":20030809,"age":20,"countryId":5,"country":"Japan","zodiacId":5,"zodiac":"Leo","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Keena","groupName":"Fifty Fifty","imageName":"KEENA_FIFTYFIFTY","birthday":"09/07/2002","birthdayNumber":20020709,"age":21,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Kelly","groupName":"TRI.BE","imageName":"KELLY_TRIBE","birthday":"16/01/2002","birthdayNumber":20020116,"age":21,"countryId":3,"country":"Taiwan","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"KimLip","groupName":"ARTMS","imageName":"KIMLIP_ARTMS","birthday":"10/02/1999","birthdayNumber":19990210,"age":24,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Kotone","groupName":"tripleS","imageName":"KOTONE_TRIPLES","birthday":"10/03/2004","birthdayNumber":20040310,"age":19,"countryId":5,"country":"Japan","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Kyujin","groupName":"NMIXX","imageName":"KYUJIN_NMIXX","birthday":"26/05/2006","birthdayNumber":20060526,"age":17,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Lara","groupName":"Dream Note","imageName":"LARA_DREAMNOTE","birthday":"09/08/2000","birthdayNumber":20000809,"age":23,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Leeseo","groupName":"IVE","imageName":"LEESEO_IVE","birthday":"21/02/2007","birthdayNumber":20070221,"age":16,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Lia","groupName":"ITZY","imageName":"LIA_ITZY","birthday":"21/07/2000","birthdayNumber":20000721,"age":23,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Lily","groupName":"NMIXX","imageName":"LILY_NMIXX","birthday":"17/10/2002","birthdayNumber":20021017,"age":21,"countryId":11,"country":"Australia","zodiacId":7,"zodiac":"Libra","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Lisa","groupName":"Blackpink","imageName":"LISA_BLACKPINK","birthday":"27/03/1997","birthdayNumber":19970327,"age":26,"countryId":1,"country":"Thailand","zodiacId":1,"zodiac":"Aries","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Liz","groupName":"IVE","imageName":"LIZ_IVE","birthday":"21/11/2004","birthdayNumber":20041121,"age":19,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Lola","groupName":"Pixy","imageName":"LOLA_PIXY","birthday":"22/02/2001","birthdayNumber":20010222,"age":22,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Lucy","groupName":"woo!ah!","imageName":"LUCY_WOOAH","birthday":"09/04/2004","birthdayNumber":20040409,"age":19,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Luda","groupName":"WJSN","imageName":"LUDA_WJSN","birthday":"06/02/1997","birthdayNumber":19970206,"age":26,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Lynn","groupName":"tripleS","imageName":"LYNN_TRIPLES","birthday":"12/04/2006","birthdayNumber":20060412,"age":17,"countryId":5,"country":"Japan","zodiacId":1,"zodiac":"Aries","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Mayu","groupName":"tripleS","imageName":"MAYU_TRIPLES","birthday":"12/05/2002","birthdayNumber":20020512,"age":21,"countryId":5,"country":"Japan","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Mia","groupName":"Everglow","imageName":"MIA_EVERGLOW","birthday":"13/01/2000","birthdayNumber":20000113,"age":23,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Minji","groupName":"NewJeans","imageName":"MINJI_NEWJEANS","birthday":"07/05/2004","birthdayNumber":20040507,"age":19,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Minju","groupName":"I\u0027LL-IT","imageName":"MINJU_ILLIT","birthday":"11/05/2004","birthdayNumber":20040511,"age":19,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Minju","groupName":"soloist","imageName":"MINJU_SOLOIST","birthday":"05/02/2001","birthdayNumber":20010205,"age":22,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Minnie","groupName":"(g)i-dle","imageName":"MINNIE_GIDLE","birthday":"23/10/1997","birthdayNumber":19971023,"age":26,"countryId":1,"country":"Thailand","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Minseo","groupName":"woo!ah!","imageName":"MINSEO_WOOAH","birthday":"12/08/2004","birthdayNumber":20040812,"age":19,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Mire","groupName":"TRI.BE","imageName":"MIRE_TRIBE","birthday":"26/03/2006","birthdayNumber":20060326,"age":17,"countryId":5,"country":"Japan","zodiacId":1,"zodiac":"Aries","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Miso","groupName":"Dream Note","imageName":"MISO_DREAMNOTE","birthday":"25/10/2000","birthdayNumber":20001025,"age":23,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Miu","groupName":"Limelight","imageName":"MIU_LIMELIGHT","birthday":"09/01/2003","birthdayNumber":20030109,"age":20,"countryId":5,"country":"Japan","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Miyeon","groupName":"(g)i-dle","imageName":"MIYEON_GIDLE","birthday":"31/01/1997","birthdayNumber":19970131,"age":26,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Moka","groupName":"I\u0027LL-IT","imageName":"MOKA_ILLIT","birthday":"08/10/2004","birthdayNumber":20041008,"age":19,"countryId":5,"country":"Japan","zodiacId":7,"zodiac":"Libra","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Momo","groupName":"Twice","imageName":"MOMO_TWICE","birthday":"09/11/1996","birthdayNumber":19961109,"age":27,"countryId":5,"country":"Japan","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Monday","groupName":"Weeekly","imageName":"MONDAY_WEEEKLY","birthday":"10/05/2002","birthdayNumber":20020510,"age":21,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Moon Sua","groupName":"Billlie","imageName":"MOONSUA_BILLLIE","birthday":"09/09/1999","birthdayNumber":19990909,"age":24,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Nagyung","groupName":"fromis_9","imageName":"NAGYUNG_FROMIS9","birthday":"01/06/2000","birthdayNumber":20000601,"age":23,"countryId":7,"country":"Souht Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Nahyun","groupName":"primrose","imageName":"NAHYUN_PRIMROSE","birthday":"25/01/2002","birthdayNumber":20020125,"age":21,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Nakyoung","groupName":"tripleS","imageName":"NAKYOUNG_TRIPLES","birthday":"13/10/2002","birthdayNumber":20021013,"age":21,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Nana","groupName":"woo!ah!","imageName":"NANA_WOOAH","birthday":"09/03/2001","birthdayNumber":20010309,"age":22,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Nancy","groupName":"Momoland","imageName":"NANCY_MOMOLAND","birthday":"13/04/2000","birthdayNumber":20000413,"age":23,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Natty","groupName":"KISS OF LIFE","imageName":"NATTY_KISSOFLIFE","birthday":"30/05/2002","birthdayNumber":20020530,"age":21,"countryId":1,"country":"Thailand","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Nayeon","groupName":"Twice","imageName":"NAYEON_TWICE","birthday":"22/09/1995","birthdayNumber":19950922,"age":28,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Nayoung","groupName":"Lightsum","imageName":"NAYOUNG_LIGHTSUM","birthday":"30/11/2002","birthdayNumber":20021130,"age":21,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Nayu","groupName":"ily:1","imageName":"NAYU_ILY1","birthday":"23/07/2002","birthdayNumber":20020723,"age":21,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Nien","groupName":"tripleS","imageName":"NIEN_TRIPLES","birthday":"02/06/2003","birthdayNumber":20030602,"age":20,"countryId":3,"country":"Taiwan","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Ning Ning","groupName":"aespa","imageName":"NINGNING_AESPA","birthday":"23/10/2002","birthdayNumber":20021023,"age":21,"countryId":4,"country":"China","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Onda","groupName":"Everglow","imageName":"ONDA_EVERGLOW","birthday":"18/05/2000","birthdayNumber":20000518,"age":23,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Rei","groupName":"IVE","imageName":"REI_IVE","birthday":"03/02/2004","birthdayNumber":20040203,"age":19,"countryId":5,"country":"Japan","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Riina","groupName":"H1-KEY","imageName":"RIINA_H1KEY","birthday":"21/02/2001","birthdayNumber":20010221,"age":22,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Ririka","groupName":"ily:1","imageName":"RIRIKA_ILY1","birthday":"02/07/2002","birthdayNumber":20020702,"age":21,"countryId":5,"country":"Japan","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Riwon","groupName":"CLASS:y","imageName":"RIWON_CLASSY","birthday":"11/01/2007","birthdayNumber":20070111,"age":16,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Rona","groupName":"ily:1","imageName":"RONA_ILY1","birthday":"05/06/2002","birthdayNumber":20020605,"age":21,"countryId":4,"country":"China","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Rora","groupName":"Babymonster","imageName":"RORA_BABYMONSTER","birthday":"14/08/2008","birthdayNumber":20080814,"age":15,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Rose","groupName":"Blackpink","imageName":"ROSE_BLACKPINK","birthday":"11/02/1997","birthdayNumber":19970211,"age":26,"countryId":6,"country":"New Zealand","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Ryujin","groupName":"ITZY","imageName":"RYUJIN_ITZY","birthday":"17/04/2001","birthdayNumber":20010417,"age":22,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Saerom","groupName":"fromis_9","imageName":"SAEROM_FROMIS9","birthday":"07/01/1997","birthdayNumber":19970107,"age":27,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Sakura","groupName":"LE SSERAFIM","imageName":"SAKURA_LESSERAFIM","birthday":"19/03/1998","birthdayNumber":19980319,"age":25,"countryId":5,"country":"Japan","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"Sana","groupName":"Twice","imageName":"SANA_TWICE","birthday":"29/12/1996","birthdayNumber":19961229,"age":27,"countryId":5,"country":"Japan","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Sangah","groupName":"Lightsum","imageName":"SANGAH_LIGHTSUM","birthday":"04/09/2002","birthdayNumber":20020904,"age":21,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Seeun","groupName":"Stayc","imageName":"SEEUN_STAYC","birthday":"14/06/2003","birthdayNumber":20030614,"age":20,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Sena","groupName":"ADYA","imageName":"SENA_ADYA","birthday":"12/10/2005","birthdayNumber":20051012,"age":18,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Seoi","groupName":"H1-KEY","imageName":"SEOI_H1KEY","birthday":"12/02/2000","birthdayNumber":20000212,"age":23,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Seola","groupName":"WJSN","imageName":"SEOLA_WJSN","birthday":"24/12/1994","birthdayNumber":19941224,"age":29,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Seonyu","groupName":"CLASS:y","imageName":"SEONYU_CLASSY","birthday":"20/03/2008","birthdayNumber":20080320,"age":15,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Seoyeon","groupName":"fromis_9","imageName":"SEOYEON_FROMIS9","birthday":"22/01/2000","birthdayNumber":20000122,"age":23,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Seoyeon","groupName":"tripleS","imageName":"SEOYEON_TRIPLES","birthday":"06/08/2003","birthdayNumber":20030806,"age":20,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Shana","groupName":"Lapillus","imageName":"SHANA_LAPILLUS","birthday":"13/03/2003","birthdayNumber":20030313,"age":20,"countryId":5,"country":"Japan","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Sheon","groupName":"Billlie","imageName":"SHEON_BILLLIE","birthday":"28/01/2003","birthdayNumber":20030128,"age":20,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Shion","groupName":"tripleS","imageName":"SHION_TRIPLES","birthday":"03/04/2006","birthdayNumber":20060403,"age":17,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Shuhua","groupName":"(g)i-dle","imageName":"SHUHUA_GIDLE","birthday":"06/01/2000","birthdayNumber":20000106,"age":24,"countryId":3,"country":"Taiwan","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Sieun","groupName":"Stayc","imageName":"SIEUN_STAYC","birthday":"01/08/2001","birthdayNumber":20010801,"age":22,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Sihyeon","groupName":"CSR","imageName":"SIHYEON_CSR","birthday":"12/03/2005","birthdayNumber":20050312,"age":18,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Sihyeon","groupName":"Everglow","imageName":"SIHYEON_EVERGLOW","birthday":"05/08/1999","birthdayNumber":19990805,"age":24,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"SinB","groupName":"VIVIZ","imageName":"SINB_VIVIZ","birthday":"03/06/1998","birthdayNumber":19980603,"age":25,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"Siyeon","groupName":"Dreamcatcher","imageName":"SIYEON_DREAMCATCHER","birthday":"01/10/1995","birthdayNumber":19951001,"age":28,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Siyoon","groupName":"Billlie","imageName":"SIYOON_BILLLIE","birthday":"16/02/2005","birthdayNumber":20050216,"age":18,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Soeun","groupName":"Weeekly","imageName":"SOEUN_WEEEKLY","birthday":"26/10/2002","birthdayNumber":20021026,"age":21,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Sohee","groupName":"ichillin","imageName":"SOHEE_ICHILLIN","birthday":"01/01/2004","birthdayNumber":20040101,"age":20,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Sohee","groupName":"Alice","imageName":"SOHEE_ALICE","birthday":"31/12/1999","birthdayNumber":19991231,"age":24,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Sohyun","groupName":"tripleS","imageName":"SOHYUN_TRIPLES","birthday":"13/10/2002","birthdayNumber":20021013,"age":21,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Sojin","groupName":"Hashtag","imageName":"SOJIN_HASHTAG","birthday":"24/09/1999","birthdayNumber":19990924,"age":24,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Somi","groupName":"soloist","imageName":"SOMI_SOLOIST","birthday":"09/03/2001","birthdayNumber":20010309,"age":22,"countryId":12,"country":"Canada","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Soodam","groupName":"Secret Number","imageName":"SOODAM_SECRETNUMBER","birthday":"09/11/1999","birthdayNumber":19991109,"age":24,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Soojin","groupName":"Weeekly","imageName":"SOOJIN_WEEEKLY","birthday":"12/12/2001","birthdayNumber":20011212,"age":22,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Soomin","groupName":"tripleS","imageName":"SOOMIN_TRIPLES","birthday":"03/10/2007","birthdayNumber":20071003,"age":16,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Sora","groupName":"woo!ah!","imageName":"SORA_WOOAH","birthday":"30/08/2003","birthdayNumber":20030830,"age":20,"countryId":5,"country":"Japan","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Sowon","groupName":"Gfriend","imageName":"SOWON_GFRIEND","birthday":"07/12/1995","birthdayNumber":19951207,"age":28,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Soyeon","groupName":"(g)i-dle","imageName":"SOYEON_GIDLE","birthday":"26/08/1998","birthdayNumber":19980826,"age":25,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"Sua","groupName":"Pixy","imageName":"SUA_PIXY","birthday":"24/02/2003","birthdayNumber":20030224,"age":20,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Sua","groupName":"Dreamcatcher","imageName":"SUA_DREAMCATCHER","birthday":"10/08/1994","birthdayNumber":19940810,"age":29,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":11,"chineseZodiac":"Dog"}
, {"artistName":"Sua","groupName":"CSR","imageName":"SUA_CSR","birthday":"23/07/2005","birthdayNumber":20050723,"age":18,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Suhye","groupName":"Limelight","imageName":"SUHYE_LIMELIGHT","birthday":"13/12/2004","birthdayNumber":20041213,"age":19,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Suhyeon","groupName":"Billlie","imageName":"SUHYEON_BILLLIE","birthday":"15/01/2000","birthdayNumber":20000115,"age":23,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Sullyoon","groupName":"NMIXX","imageName":"SULLYOON_NMIXX","birthday":"26/01/2004","birthdayNumber":20040126,"age":19,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Sumin","groupName":"Stayc","imageName":"SUMIN_STAYC","birthday":"13/03/2001","birthdayNumber":20010313,"age":22,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Sumin","groupName":"Dream Note","imageName":"SUMIN_DREAMNOTE","birthday":"07/09/2001","birthdayNumber":20010907,"age":22,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Suyun","groupName":"Rocket Punch","imageName":"SUYUN_ROCKETPUNCH","birthday":"17/03/2001","birthdayNumber":20010317,"age":22,"countryId":2,"country":"South Korea","zodiacId":12,"zodiac":"Pisces","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Swan","groupName":"Purple Kiss","imageName":"SWAN_PURPLEKISS","birthday":"11/07/2003","birthdayNumber":20030711,"age":20,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Takara","groupName":"Busters","imageName":"TAKARA_BUSTERS","birthday":"19/01/2005","birthdayNumber":20050119,"age":18,"countryId":5,"country":"Japan","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Tsuki","groupName":"Billlie","imageName":"TSUKI_BILLLIE","birthday":"21/09/2002","birthdayNumber":20020921,"age":21,"countryId":5,"country":"Japan","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Tzuyu","groupName":"Twice","imageName":"TZUYU_TWICE","birthday":"14/06/1999","birthdayNumber":19990614,"age":24,"countryId":3,"country":"Taiwan","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Umji","groupName":"VIVIZ","imageName":"UMJI_VIVIZ","birthday":"19/08/1998","birthdayNumber":19980819,"age":25,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":3,"chineseZodiac":"Tiger"}
, {"artistName":"Vivi","groupName":"LOOSSEMBLE","imageName":"VIVI_LOOSSEMBLE","birthday":"09/12/1996","birthdayNumber":19961209,"age":27,"countryId":10,"country":"Hong Kong","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Winter","groupName":"aespa","imageName":"WINTER_AESPA","birthday":"01/01/2001","birthdayNumber":20010101,"age":23,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Wonhee","groupName":"I\u0027LL-IT","imageName":"WONHEE_ILLIT","birthday":"26/06/2007","birthdayNumber":20070626,"age":16,"countryId":2,"country":"South Korea","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Wonyoung","groupName":"IVE","imageName":"WONYOUNG_IVE","birthday":"31/08/2004","birthdayNumber":20040831,"age":19,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Wooyeon","groupName":"woo!ah!","imageName":"WOOYEON_WOOAH","birthday":"11/02/2003","birthdayNumber":20030211,"age":20,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Xiaoting","groupName":"Kep1er","imageName":"XIAOTING_KEP1ER","birthday":"12/11/1999","birthdayNumber":19991112,"age":24,"countryId":4,"country":"China","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Xinyu","groupName":"tripleS","imageName":"XINYU_TRIPLES","birthday":"25/05/2002","birthdayNumber":20020525,"age":21,"countryId":4,"country":"China","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Yaning","groupName":"others","imageName":"YANING_OTHERS","birthday":"14/07/1997","birthdayNumber":19970714,"age":26,"countryId":4,"country":"China","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Yeji","groupName":"ITZY","imageName":"YEJI_ITZY","birthday":"26/05/2000","birthdayNumber":20000526,"age":23,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Yeju","groupName":"ichillin","imageName":"YEJU_ICHILLIN","birthday":"01/09/2004","birthdayNumber":20040901,"age":19,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Yel","groupName":"H1-KEY","imageName":"YEL_H1KEY","birthday":"25/12/2004","birthdayNumber":20041225,"age":19,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Yena","groupName":"soloist","imageName":"YENA_SOLOIST","birthday":"29/09/1999","birthdayNumber":19990929,"age":24,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Yeojin","groupName":"LOOSSEMBLE","imageName":"YEOJIN_LOOSSEMBLE","birthday":"11/11/2002","birthdayNumber":20021111,"age":21,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Yeonhee","groupName":"Rocket Punch","imageName":"YEONHEE_ROCKETPUNCH","birthday":"06/12/2000","birthdayNumber":20001206,"age":23,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Yeonji","groupName":"tripleS","imageName":"YEONJI_TRIPLES","birthday":"08/01/2008","birthdayNumber":20080108,"age":16,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Yeonjung","groupName":"WJSN","imageName":"YEONJUNG_WJSN","birthday":"10/01/1999","birthdayNumber":19990110,"age":24,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Yeoreum","groupName":"WJSN","imageName":"YEOREUM_WJSN","birthday":"03/08/1999","birthdayNumber":19990803,"age":24,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Yeram","groupName":"others","imageName":"YERAM_OTHERS","countryId":2,"country":"South Korea"}
, {"artistName":"Yerin","groupName":"Gfriend","imageName":"YERIN_GFRIEND","birthday":"19/08/1996","birthdayNumber":19960819,"age":27,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Yeseo","groupName":"Kep1er","imageName":"YESEO_KEP1ER","birthday":"22/08/2005","birthdayNumber":20050822,"age":18,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Yiren","groupName":"Everglow","imageName":"YIREN_EVERGLOW","birthday":"29/12/2000","birthdayNumber":20001229,"age":23,"countryId":4,"country":"China","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Yooa","groupName":"Oh My Girl","imageName":"YOOA_OHMYGIRL","birthday":"17/09/1995","birthdayNumber":19950917,"age":28,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":12,"chineseZodiac":"Pig"}
, {"artistName":"Yoohyeon","groupName":"Dreamcatcher","imageName":"YOOHYEON_DREAMCATCHER","birthday":"07/01/1997","birthdayNumber":19970107,"age":27,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Yoon","groupName":"Stayc","imageName":"YOON_STAYC","birthday":"14/04/2004","birthdayNumber":20040414,"age":19,"countryId":2,"country":"South Korea","zodiacId":1,"zodiac":"Aries","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Yooyeon","groupName":"tripleS","imageName":"YOOYEON_TRIPLES","birthday":"09/02/2001","birthdayNumber":20010209,"age":22,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"YOUI","groupName":"Dream Note","imageName":"YOUI_DREAMNOTE","birthday":"24/04/2000","birthdayNumber":20000424,"age":23,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":5,"chineseZodiac":"Dragon"}
, {"artistName":"Youngeun","groupName":"Kep1er","imageName":"YOUNGEUN_KEP1ER","birthday":"27/12/2004","birthdayNumber":20041227,"age":19,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Youngseo","groupName":"I\u0027LL-IT","imageName":"YOUNGSEO_ILLIT","birthday":"13/11/2005","birthdayNumber":20051113,"age":18,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Yubin","groupName":"Oh My Girl","imageName":"YUBIN_OHMYGIRL","birthday":"09/09/1997","birthdayNumber":19970909,"age":26,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Yubin","groupName":"tripleS","imageName":"YUBIN_TRIPLES","birthday":"03/02/2005","birthdayNumber":20050203,"age":18,"countryId":2,"country":"South Korea","zodiacId":11,"zodiac":"Aquarius","chineseZodiacId":10,"chineseZodiac":"Rooster"}
, {"artistName":"Yue","groupName":"Lapillus","imageName":"YUE_LAPILLUS","birthday":"03/07/2004","birthdayNumber":20040703,"age":19,"countryId":8,"country":"USA","zodiacId":4,"zodiac":"Cancer","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Yujeong","groupName":"Brave Girls","imageName":"YUJEONG_BRAVEGIRLS","birthday":"02/05/1991","birthdayNumber":19910502,"age":32,"countryId":2,"country":"South Korea","zodiacId":2,"zodiac":"Taurus","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Yujin","groupName":"Kep1er","imageName":"YUJIN_KEP1ER","birthday":"12/08/1996","birthdayNumber":19960812,"age":27,"countryId":2,"country":"South Korea","zodiacId":5,"zodiac":"Leo","chineseZodiacId":1,"chineseZodiac":"Rat"}
, {"artistName":"Yujin","groupName":"IVE","imageName":"YUJIN_IVE","birthday":"01/09/2003","birthdayNumber":20030901,"age":20,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Yuju","groupName":"Gfriend","imageName":"YUJU_GFRIEND","birthday":"04/10/1997","birthdayNumber":19971004,"age":26,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Yuki","groupName":"Purple Kiss","imageName":"YUKI_PURPLEKISS","birthday":"06/11/2002","birthdayNumber":20021106,"age":21,"countryId":5,"country":"Japan","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":7,"chineseZodiac":"Horse"}
, {"artistName":"Yuna","groupName":"ITZY","imageName":"YUNA_ITZY","birthday":"09/12/2003","birthdayNumber":20031209,"age":20,"countryId":2,"country":"South Korea","zodiacId":9,"zodiac":"Sagittarius","chineseZodiacId":8,"chineseZodiac":"Goat"}
, {"artistName":"Yunah","groupName":"I\u0027LL-IT","imageName":"YUNAH_ILLIT","birthday":"15/01/2004","birthdayNumber":20040115,"age":19,"countryId":2,"country":"South Korea","zodiacId":10,"zodiac":"Capricorn","chineseZodiacId":9,"chineseZodiac":"Monkey"}
, {"artistName":"Yunjin","groupName":"LE SSERAFIM","imageName":"YUNJIN_LESSERAFIM","birthday":"08/10/2001","birthdayNumber":20011008,"age":22,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Yunkyoung","groupName":"Rocket Punch","imageName":"YUNKYOUNG_ROCKETPUNCH","birthday":"01/11/2001","birthdayNumber":20011101,"age":22,"countryId":2,"country":"South Korea","zodiacId":8,"zodiac":"Scorpius","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Yuqi","groupName":"(g)i-dle","imageName":"YUQI_GIDLE","birthday":"23/09/1999","birthdayNumber":19990923,"age":24,"countryId":4,"country":"China","zodiacId":7,"zodiac":"Libra","chineseZodiacId":4,"chineseZodiac":"Rabbit"}
, {"artistName":"Yuri","groupName":"soloist","imageName":"YURI_SOLOIST","birthday":"22/10/2001","birthdayNumber":20011022,"age":22,"countryId":2,"country":"South Korea","zodiacId":7,"zodiac":"Libra","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Yves","groupName":"soloist","imageName":"YVES_SOLOIST","birthday":"24/05/1997","birthdayNumber":19970524,"age":26,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":2,"chineseZodiac":"Ox"}
, {"artistName":"Zin","groupName":"bugAboo","imageName":"ZIN_BUGABOO","birthday":"30/08/2001","birthdayNumber":20010830,"age":22,"countryId":2,"country":"South Korea","zodiacId":6,"zodiac":"Virgo","chineseZodiacId":6,"chineseZodiac":"Snake"}
, {"artistName":"Zoa","groupName":"Weeekly","imageName":"ZOA_WEEEKLY","birthday":"31/05/2005","birthdayNumber":20050531,"age":18,"countryId":2,"country":"South Korea","zodiacId":3,"zodiac":"Gemini","chineseZodiacId":10,"chineseZodiac":"Rooster"}

];

